version: "3.8"
services:
  client:
    container_name: jax-pet-names-client
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/client_app
      - /client_app/node_modules
