version: "3.8"
services:
  client:
    container_name: jax-pet-names-client
    restart: on-failure
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_HOST: "http://localhost:3001"
    volumes:
      - ./:/client_app
      - /client_app/client/node_modules
  server:
    container_name: jax-pet-names-server
    restart: on-failure
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_URL: "postgresql://postgres:postgres@db:5432/pet_names"
      DB_SETUP_URL: "postgresql://postgres:postgres@db:5432"
    volumes:
      - ./:/server_app
      - /server_app/server/node_modules
  db:
    container_name: jax-pet-names-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
