version: "3.8"
services:
  server:
    container_name: jax-pet-names-server
    restart: on-failure
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./:/server_app
      - /server_app/node_modules
  db:
    container_name: jax-pet-names-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
