name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
    - run: npm ci
    - run: docker compose build
    - run: docker compose up --detach
    - uses: nick-fields/retry@v3
      with:
        timeout_seconds: 15
        max_attempts: 3
        retry_on: error
        command: docker exec -i jax-pet-names-server npm run db:setup
    - run: npm run cypress:run

  server-test-job:
    runs-on: ubuntu-latest
    env:
      DB_URL: postgresql://postgres:postgres@localhost:5432/pet_names
      DB_SETUP_URL: postgresql://postgres:postgres@localhost:5432
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
    - run: npm ci
      working-directory: ./server
    - run: docker run -p 5432:5432 --name jax-pet-names-pg -e POSTGRES_PASSWORD=postgres -d postgres
      working-directory: ./server
    - uses: nick-fields/retry@v3
      with:
        timeout_seconds: 15
        max_attempts: 3
        retry_on: error
        command: cd server && npm run db:reset
    - run: npm test
      working-directory: ./server
